### ISSUE TITLE
Rate limited when using `AccountKit` alongside `Privy`

### ISSUE THREAD

**Issue by salieflewis** [alchemyplatform/aa-sdk#245]
Thanks for filling out this bug report. Please provide as much detail as possible.

I'm noticing that [my implementation](https://github.com/1ifeworld/river/blob/main/apps/site/context/AlchemyProviderContext.tsx) of `AccountKit` is spamming the `alchemy_requestGasAndPaymasterAndData` method about three times before either failing or going through. I'm using an API key on the Free tier, but I hope that being on the Growth tier is not necessary in order to use this SDK bug-free.

If your issue is with Alchemy's RPC APIs and not the SDK please report your issue on (discord)[https://alchemy.com/discord].

### [REQUIRED] Environment

- Browser version:
- AA SDK version:
- Package:
```
 "@alchemy/aa-accounts": "^0.1.1",
 "@alchemy/aa-alchemy": "^0.1.1",
 "@alchemy/aa-core": "^0.1.1",
 "alchemy-sdk": "^2.10.0",
```

#### Relevant code or sample repro:

Linked above.

**Comment by salieflewis** [comment]
cc: @denniswon @avasisht23

**Comment by robzajac** [comment]
Hey @salieflewis thanks for opening this! This is a known issue on our end where `alchemy_requestGasAndPaymasterAndData` is being rate-limited on the free tier due to the throughput limit on that tier. Your app is probably retrying several times when it sees the 429 (hence the multiple calls), and one of those requests may go through as we allow exactly 1 request over the throughput limit per second. You can read more about our throughput model [here](https://docs.alchemy.com/reference/throughput).
We have a fix planned to allow more calls to go through on the free tier. For now I would recommend going to Growth for more testing, and we will try to unblock Free ASAP. Thanks for your patience! 🙏

**Comment by salieflewis** [comment]
> Hey @salieflewis thanks for opening this! This is a known issue on our end where `alchemy_requestGasAndPaymasterAndData` is being rate-limited on the free tier due to the throughput limit on that tier. Your app is probably retrying several times when it sees the 429 (hence the multiple calls), and one of those requests may go through as we allow exactly 1 request over the throughput limit per second. You can read more about our throughput model [here](https://docs.alchemy.com/reference/throughput). We have a fix planned to allow more calls to go through on the free tier. For now I would recommend going to Growth for more testing, and we will try to unblock Free ASAP. Thanks for your patience! 🙏

Thanks for letting me know. As a workaround, is there a way to slot in another RPC provider?

**Comment by robzajac** [comment]
Hey @salieflewis, just an update that we've pushed a fix to unblock this on the free tier. You should be able to spend user ops without reaching a throughput limit. Let me know if we can help with anything else! 🙏

**Comment by salieflewis** [comment]
Hi, apologies for not responding sooner. I've yet to put this to the test as I actually went ahead and moved into the Growth tier ahead of this response. Does anything need to happen on my end ( i.e. updating packages)? Will definitely hit you up if anything else arises, thanks very much!

**Comment by avasisht23** [comment]
As long as your Alchemy API Key is associated with the Alchemy account on Growth Tier, no other changes are needed!
